BORLAND_DEST	= /mnt/c/bc4/source/libcmmn

BORLAND_BUILD	= common.ide

COMMON_SOURCES	=	\
	argbool.c	\
	argdbl.c	\
	argflag.c	\
	argint.c	\
	arglong.c	\
	argstr.c	\
	avl.c		\
	cntrline.c	\
	cmmngver.c	\
	dstrftmt.c	\
	dstrttm.c	\
	dstrttmt.c	\
	dttmdata.c	\
	difftm.c	\
	etoa.c		\
	errstr.c	\
	findpath.c	\
	hmstmt.c	\
	islpyr.c	\
	liberr.c	\
	llvlfstr.c	\
	llvlstr.c	\
	logger.c	\
	loginit.c	\
	logloc.c	\
	logtee.c	\
	logtrim.c	\
	serrhdlr.c	\
	strdbl.c	\
	strint.c	\
	strlng.c	\
	strshrt.c	\
	struint.c	\
	strulong.c	\
	strushrt.c	\
	strpspc.c	\
	ymddtmt.c	\
	yymddtmt.c	\
	ymdtmt.c	\
	_argstr.c	\
	_logfn.c	\
	datetime.h	\
	bit.h		\
	cmmnver.h	\
	common.h	\
	cmmnprot.h	\
	_common.h	\
	_avltyps.h	\
	strdup.c	\
	strupr.c	\
	strlwr.c	\
	basename.c	\
	strptime.c	\

BORLAND_SOURCES = 	\
	canexec.c	\
	fmdstr.c	\
	freafile.c	\
	cmmncfg.h	\

COMMON_DIFFS	=	\
	argbool.c.diff	\
	argdbl.c.diff	\
	argflag.c.diff	\
	argint.c.diff	\
	arglong.c.diff	\
	argstr.c.diff	\
	avl.c.diff	\
	cntrline.c.diff	\
	cmmngver.c.diff	\
	dstrftmt.c.diff	\
	dstrttm.c.diff	\
	dstrttmt.c.diff	\
	dttmdata.c.diff	\
	difftm.c.diff	\
	etoa.c.diff	\
	errstr.c.diff	\
	findpath.c.diff	\
	hmstmt.c.diff	\
	islpyr.c.diff	\
	liberr.c.diff	\
	llvlfstr.c.diff	\
	llvlstr.c.diff	\
	logger.c.diff	\
	loginit.c.diff	\
	logloc.c.diff	\
	logtee.c.diff	\
	logtrim.c.diff	\
	serrhdlr.c.diff	\
	strdbl.c.diff	\
	strint.c.diff	\
	strlng.c.diff	\
	strshrt.c.diff	\
	struint.c.diff	\
	strulong.c.diff	\
	strushrt.c.diff	\
	strpspc.c.diff	\
	ymddtmt.c.diff	\
	yymddtmt.c.diff	\
	ymdtmt.c.diff	\
	_argstr.c.diff	\
	_logfn.c.diff	\
	datetime.h.diff	\
	bit.h.diff	\
	cmmnver.h.diff	\
	common.h.diff	\
	cmmnprot.h.diff	\
	_common.h.diff	\
	_avltyps.h.diff	\
	strdup.c.diff	\
	strupr.c.diff	\
	strlwr.c.diff	\
	basename.c.diff	\
	strptime.c.diff	\


argbool.c:	../../Common/ArgEnvBool.c
	cp $? $@

argdbl.c:	../../Common/ArgEnvDouble.c
	cp $? $@

argflag.c:	../../Common/ArgEnvFlag.c
	cp $? $@

argint.c:	../../Common/ArgEnvInt.c
	cp $? $@

arglong.c:	../../Common/ArgEnvLong.c
	cp $? $@

argstr.c:	../../Common/ArgEnvString.c
	cp $? $@

avl.c:		../../Common/Avl.c
	cp $? $@

cntrline.c:	../../Common/CenterLine.c
	cp $? $@

cmmngver.c:	../../Common/CommonGetVersion.c
	cp $? $@

dstrftmt.c:	../../Common/DateStringFromTimeT.c
	cp $? $@

dstrttm.c:	../../Common/DateStringFromTm.c
	cp $? $@

dstrttmt.c:	../../Common/DateStringToTimeT.c
	cp $? $@

dttmdata.c:	../../Common/DateTimeData.c
	cp $? $@

difftm.c:	../../Common/Difftm.c
	cp $? $@

etoa.c:		../../Common/EbcdicToAscii.c
	cp $? $@

errstr.c:	../../Common/ErrorString.c
	cp $? $@

findpath.c:	../../Common/FindPath.c
	cp $? $@

hmstmt.c:	../../Common/HHMMSStoTimeT.c
	cp $? $@

islpyr.c:	../../Common/IsLeapYear.c
	cp $? $@

liberr.c:	../../Common/LibError.c
	cp $? $@

llvlfstr.c:	../../Common/LogLevelFromString.c
	cp $? $@

llvlstr.c:	../../Common/LogLevelString.c
	cp $? $@

logger.c:	../../Common/Logger.c
	cp $? $@

loginit.c:	../../Common/LoggerInit.c
	cp $? $@

logloc.c:	../../Common/LoggerLoc.c
	cp $? $@

logtee.c:	../../Common/LoggerTee.c
	cp $? $@

logtrim.c:	../../Common/LoggerTrim.c
	cp $? $@

serrhdlr.c:	../../Common/SetErrorHandler.c
	cp $? $@

strdbl.c:	../../Common/StringToDouble.c
	cp $? $@

strint.c:	../../Common/StringToInt.c
	cp $? $@

strlng.c:	../../Common/StringToLong.c
	cp $? $@

strshrt.c:	../../Common/StringToShort.c
	cp $? $@

struint.c:	../../Common/StringToUInt.c
	cp $? $@

strulong.c:	../../Common/StringToULong.c
	cp $? $@

strushrt.c:	../../Common/StringToUShort.c
	cp $? $@

strpspc.c:	../../Common/StripSpaces.c
	cp $? $@

ymddtmt.c:	../../Common/YYMMDDtoTimeT.c
	cp $? $@

yymddtmt.c:	../../Common/YYYYMMDDtoTimeT.c
	cp $? $@

ymdtmt.c:	../../Common/YearMonthDayToTimeT.c
	cp $? $@

_argstr.c:	../../Common/_ArgString.c
	cp $? $@

_logfn.c:	../../Common/_LoggerFileName.c
	cp $? $@

datetime.h:	../../Common/DateTime.h
	cp $? $@

bit.h:		../../Common/Bit.h
	cp $? $@

common.h:	../../Common/Common.h
	cp $? $@

cmmnver.h:	../../Common/CommonVersion.h
	cp $? $@

cmmnprot.h:	../../Common/_Common_Proto.h
	cp $? $@

_common.h:	../../Common/_Common.h
	cp $? $@

_avltyps.h:	../../Common/_AvlTypes.h
	cp $? $@

strdup.c:	../src/strdup.c
	cp $? $@

strlwr.c:	../src/strlwr.c
	cp $? $@

strupr.c:	../src/strupr.c
	cp $? $@

basename.c:	../src/basename.c
	cp $? $@

strptime.c:	../src/strptime.c
	cp $? $@



argbool.c.diff:
	cp argbool.c Patch/Common/ArgEnvBool.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvBool.c \
	Common/ArgEnvBool.c >../argbool.c.diff )

argdbl.c.diff:
	cp argdbl.c Patch/Common/ArgEnvDouble.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvDouble.c \
	Common/ArgEnvDouble.c >../argdbl.c.diff )

argflag.c.diff:
	cp argflag.c Patch/Common/ArgEnvFlag.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvFlag.c \
	Common/ArgEnvFlag.c >../argflag.c.diff )

argint.c.diff:
	cp argint.c Patch/Common/ArgEnvInt.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvInt.c \
	Common/ArgEnvInt.c >../argint.c.diff )

arglong.c.diff:
	cp arglong.c Patch/Common/ArgEnvLong.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvLong.c \
	Common/ArgEnvLong.c >../arglong.c.diff )

argstr.c.diff:
	cp argstr.c Patch/Common/ArgEnvString.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ArgEnvString.c \
	Common/ArgEnvString.c >../argstr.c.diff )

avl.c.diff:
	cp avl.c Patch/Common/Avl.c
	-(cd Patch; \
	diff -cw \
	../../../Common/Avl.c \
	Common/Avl.c >../avl.c.diff )

cntrline.c.diff:
	cp cntrline.c Patch/Common/CenterLine.c
	-(cd Patch; \
	diff -cw \
	../../../Common/CenterLine.c \
	Common/CenterLine.c >../cntrline.c.diff )

cmmngver.c.diff:
	cp cmmngver.c Patch/Common/CommonGetVersion.c
	-(cd Patch; \
	diff -cw \
	../../../Common/CommonGetVersion.c \
	Common/CommonGetVersion.c >../cmmngver.c.diff )

dstrftmt.c.diff:
	cp dstrftmt.c Patch/Common/DateStringFromTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/DateStringFromTimeT.c \
	Common/DateStringFromTimeT.c >../dstrftmt.c.diff )

dstrttm.c.diff:
	cp dstrttm.c Patch/Common/DateStringFromTm.c
	-(cd Patch; \
	diff -cw \
	../../../Common/DateStringFromTm.c \
	Common/DateStringFromTm.c >../dstrttm.c.diff )

dstrttmt.c.diff:
	cp dstrttmt.c Patch/Common/DateStringToTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/DateStringToTimeT.c \
	Common/DateStringToTimeT.c >../dstrttmt.c.diff )

dttmdata.c.diff:
	cp dttmdata.c Patch/Common/DateTimeData.c
	-(cd Patch; \
	diff -cw \
	../../../Common/DateTimeData.c \
	Common/DateTimeData.c >../dttmdata.c.diff )

difftm.c.diff:
	cp difftm.c Patch/Common/Difftm.c
	-(cd Patch; \
	diff -cw \
	../../../Common/Difftm.c \
	Common/Difftm.c >../difftm.c.diff )

etoa.c.diff:
	cp etoa.c Patch/Common/EbcdicToAscii.c
	-(cd Patch; \
	diff -cw \
	../../../Common/EbcdicToAscii.c \
	Common/EbcdicToAscii.c >../etoa.c.diff )

errstr.c.diff:
	cp errstr.c Patch/Common/ErrorString.c
	-(cd Patch; \
	diff -cw \
	../../../Common/ErrorString.c \
	Common/ErrorString.c >../errstr.c.diff )

findpath.c.diff:
	cp findpath.c Patch/Common/FindPath.c
	-(cd Patch; \
	diff -cw \
	../../../Common/FindPath.c \
	Common/FindPath.c >../findpath.c.diff )

hmstmt.c.diff:
	cp hmstmt.c Patch/Common/HHMMSStoTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/HHMMSStoTimeT.c \
	Common/HHMMSStoTimeT.c >../hmstmt.c.diff )

islpyr.c.diff:
	cp islpyr.c Patch/Common/IsLeapYear.c
	-(cd Patch; \
	diff -cw \
	../../../Common/IsLeapYear.c \
	Common/IsLeapYear.c >../islpyr.c.diff )

liberr.c.diff:
	cp liberr.c Patch/Common/LibError.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LibError.c \
	Common/LibError.c >../liberr.c.diff )

llvlfstr.c.diff:
	cp llvlfstr.c Patch/Common/LogLevelFromString.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LogLevelFromString.c \
	Common/LogLevelFromString.c >../llvlfstr.c.diff )

llvlstr.c.diff:
	cp llvlstr.c Patch/Common/LogLevelString.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LogLevelString.c \
	Common/LogLevelString.c >../llvlstr.c.diff )

logger.c.diff:
	cp logger.c Patch/Common/Logger.c
	-(cd Patch; \
	diff -cw \
	../../../Common/Logger.c \
	Common/Logger.c >../logger.c.diff )

loginit.c.diff:
	cp loginit.c Patch/Common/LoggerInit.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LoggerInit.c \
	Common/LoggerInit.c >../loginit.c.diff )

logloc.c.diff:
	cp logloc.c Patch/Common/LoggerLoc.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LoggerLoc.c \
	Common/LoggerLoc.c >../logloc.c.diff )

logtee.c.diff:
	cp logtee.c Patch/Common/LoggerTee.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LoggerTee.c \
	Common/LoggerTee.c >../logtee.c.diff )

logtrim.c.diff:
	cp logtrim.c Patch/Common/LoggerTrim.c
	-(cd Patch; \
	diff -cw \
	../../../Common/LoggerTrim.c \
	Common/LoggerTrim.c >../logtrim.c.diff )

serrhdlr.c.diff:
	cp serrhdlr.c Patch/Common/SetErrorHandler.c
	-(cd Patch; \
	diff -cw \
	../../../Common/SetErrorHandler.c \
	Common/SetErrorHandler.c >../serrhdlr.c.diff )

strdbl.c.diff:
	cp strdbl.c Patch/Common/StringToDouble.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToDouble.c \
	Common/StringToDouble.c >../strdbl.c.diff )

strint.c.diff:
	cp strint.c Patch/Common/StringToInt.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToInt.c \
	Common/StringToInt.c >../strint.c.diff )

strlng.c.diff:
	cp strlng.c Patch/Common/StringToLong.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToLong.c \
	Common/StringToLong.c >../strlng.c.diff )

strshrt.c.diff:
	cp strshrt.c Patch/Common/StringToShort.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToShort.c \
	Common/StringToShort.c >../strshrt.c.diff )

struint.c.diff:
	cp struint.c Patch/Common/StringToUInt.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToUInt.c \
	Common/StringToUInt.c >../struint.c.diff )

strulong.c.diff:
	cp strulong.c Patch/Common/StringToULong.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToULong.c \
	Common/StringToULong.c >../strulong.c.diff )

strushrt.c.diff:
	cp strushrt.c Patch/Common/StringToUShort.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StringToUShort.c \
	Common/StringToUShort.c >../strushrt.c.diff )

strpspc.c.diff:
	cp strpspc.c Patch/Common/StripSpaces.c
	-(cd Patch; \
	diff -cw \
	../../../Common/StripSpaces.c \
	Common/StripSpaces.c >../strpspc.c.diff )

ymddtmt.c.diff:
	cp ymddtmt.c Patch/Common/YYMMDDtoTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/YYMMDDtoTimeT.c \
	Common/YYMMDDtoTimeT.c >../ymddtmt.c.diff )

yymddtmt.c.diff:
	cp yymddtmt.c Patch/Common/YYYYMMDDtoTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/YYYYMMDDtoTimeT.c \
	Common/YYYYMMDDtoTimeT.c >../yymddtmt.c.diff )

ymdtmt.c.diff:
	cp ymdtmt.c Patch/Common/YearMonthDayToTimeT.c
	-(cd Patch; \
	diff -cw \
	../../../Common/YearMonthDayToTimeT.c \
	Common/YearMonthDayToTimeT.c >../ymdtmt.c.diff )

_argstr.c.diff:
	cp _argstr.c Patch/Common/_ArgString.c
	-(cd Patch; \
	diff -cw \
	../../../Common/_ArgString.c \
	Common/_ArgString.c >../_argstr.c.diff )

_logfn.c.diff:
	cp _logfn.c Patch/Common/_LoggerFileName.c
	-(cd Patch; \
	diff -cw \
	../../../Common/_LoggerFileName.c \
	Common/_LoggerFileName.c >../_logfn.c.diff )

datetime.h.diff:
	cp datetime.h Patch/Common/DateTime.h
	-(cd Patch; \
	diff -cw \
	../../../Common/DateTime.h \
	Common/DateTime.h >../datetime.h.diff )

bit.h.diff:
	cp bit.h Patch/Common/Bit.h
	-(cd Patch; \
	diff -cw \
	../../../Common/Bit.h \
	Common/Bit.h >../bit.h.diff )

common.h.diff:
	cp common.h Patch/Common/Common.h
	-(cd Patch; \
	diff -cw \
	../../../Common/Common.h \
	Common/Common.h >../common.h.diff )

cmmnver.h.diff:
	cp cmmnver.h Patch/Common/CommonVersion.h
	-(cd Patch; \
	diff -cw \
	../../../Common/CommonVersion.h \
	Common/CommonVersion.h >../cmmnver.h.diff )

cmmnprot.h.diff:
	cp cmmnprot.h Patch/Common/_Common_Proto.h
	-(cd Patch; \
	diff -cw \
	../../../Common/_Common_Proto.h \
	Common/_Common_Proto.h >../cmmnprot.h.diff )

_common.h.diff:
	cp _common.h Patch/Common/_Common.h
	-(cd Patch; \
	diff -cw \
	../../../Common/_Common.h \
	Common/_Common.h >../_common.h.diff )

_avltyps.h.diff:
	cp _avltyps.h Patch/Common/_AvlTypes.h
	-(cd Patch; \
	diff -cw \
	../../../Common/_AvlTypes.h \
	Common/_AvlTypes.h >../_avltyps.h.diff )

strdup.c.diff:
	cp strdup.c Patch/arch/src/strdup.c
	-(cd Patch; \
	diff -cw \
	../../../arch/src/strdup.c \
	arch/src/strdup.c >../strdup.c.diff )

strlwr.c.diff:
	cp strlwr.c Patch/arch/src/strlwr.c
	-(cd Patch; \
	diff -cw \
	../../../arch/src/strlwr.c \
	arch/src/strlwr.c >../strlwr.c.diff )

strupr.c.diff:
	cp strupr.c Patch/arch/src/strupr.c
	-(cd Patch; \
	diff -cw \
	../../../arch/src/strupr.c \
	arch/src/strupr.c >../strupr.c.diff )

basename.c.diff:
	cp basename.c Patch/arch/src/basename.c
	-(cd Patch; \
	diff -cw \
	../../../arch/src/basename.c \
	arch/src/basename.c >../basename.c.diff )

strptime.c.diff:
	cp strptime.c Patch/arch/src/strptime.c
	-(cd Patch; \
	diff -cw \
	../../../arch/src/strptime.c \
	arch/src/strptime.c >../strptime.c.diff )


borland: $(COMMON_SOURCES)
	cp $(COMMON_SOURCES) $(BORLAND_SOURCES) $(BORLAND_DEST)/src
	cp $(BORLAND_BUILD) $(BORLAND_DEST)

clean:
	rm -f $(COMMON_SOURCES) patch
	rm -rf Patch

Patch:
	-mkdir Patch
	-mkdir Patch/Common
	-mkdir Patch/arch
	-mkdir Patch/arch/src
	( bdir=`pwd`; \
	  cd $(BORLAND_DEST)/src; \
	  cp $(COMMON_SOURCES) $(BORLAND_SOURCES) $$bdir; \
	  cd $(BORLAND_DEST); \
	  cp $(BORLAND_BUILD) $$bdir ) \

patch: Patch $(COMMON_DIFFS)
	cat $(COMMON_DIFFS) >patch
	rm -f $(COMMON_DIFFS)
	rm -rf Patch

