.\"
.\" Man page for AvlDelMax
.\"
.\" $Id$
.\"
.\" $Log$
.\"
.TH AvlDelMax 3  "26 Jun 94 (Common)"
.SH NAME
AvlDelMax \- remove the largest item from an AVL tree
.SH SYNOPSIS
#include <Common.h>
.LP
void * AvlDelMax(
.PD 0
.RS
.TP 10
AvlTree
tree )
.PD
.RE
.SH ARGUMENTS
tree
the tree to remove the largest node from.
.SH DESCRIPTION
AvlDelMax will remove the largest node
(according the the compare function)
from the given tree and return the pointer that was
passed to AvlAdd(3).
.SH RETURNS
the pointer that was passed to AvlAdd(3).
.SH FILES
.nf
/usr/local/include/Common.h
/usr/local/lib/libCommon.a
.fn
.SH "SEE ALSO"
AvlInit(3), AvlAttach(3), , AvlAdd(3), AvlFind(3), AvlDel(3), AvlGetRoot(3),
AvlDispose(3), AvlWalk(3), AvlCount(3), AvlDelMin(3), AvlFindMin(3),
AvlFindMax(3), Common(3)
.SH AUTHORS
.PD 0
Brad Appleton - <brad@ssd.csd.Harris.COM>,
.LP
Paul Houghton - (houghton@cworld.wiltel.com) 

