.\"
.\" Man page for CenterLine
.\"
.\" $Id$
.\"
.\" $Log$
.\"
.TH CenterLine 3  "22 Jun 94"
.SH NAME
CenterLine \- center a string by prefixing it with spaces
.SH SYNOPSIS
#include <Common.h>
.LP
char *
CenterLine(
.PD 0
.RS
.TP 15
char *
dest,
.TP 15
const char *
source,
.TP 15
int
width )
.PD
.RE
.SH ARGUMENTS
.TP
dest
the buffer to put the centered string into.
.TP
source
the character string to be centered
.TP
width
the width the string should be centered to.
.SH DESCRIPTION
Center the source string in the dest buffer by prefixing it with spaces.
.SH RETURNS
the dest pointer
.SH FILES
.nf
/usr/local/include/Common.h
/usr/local/lib/libCommon.a
.fn
.SH "SEE ALSO"
Common(3), StripSpaces(3)
.SH AUTHORS
Paul Houghton - (houghton@cworld.wiltel.com) 

