.\"
.\" Man page for CommonGetVersion
.\"
.\" $Id$
.\"
.\" $Log$
.\" Revision 2.0  1995/10/28 17:34:40  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.1  1994/07/05  21:37:59  houghton
.\" Updated man pages for all libCommon functions.
.\"
.\"
.TH CommonGetVersion 3  "26 Jun 94 (Common)"
.SH NAME
CommonGetVersion \- return the version information string for libCommon
.SH SYNOPSIS
#include <Common.h>
.LP
const char * CommonGetVersion( void )
.SH ARGUMENTS
None
.SH DESCRIPTION
Returns a string that describes the version of libCommon being
used. the string includes the cvs(1) version number and
the build date.
.SH RETURNS
char * version info
.SH FILES
.nf
%INSTALL_INC_DIR%/Common.h
%INSTALL_LIB_DIR%/libCommon.a
.fn
.SH "SEE ALSO"
Common(3)
.SH AUTHORS
Paul Houghton - (houghton@cworld.wiltel.com) 

