.\"
.\" File:      IS_BASE_DIGIT.3
.\" Project:   Common
.\" Desc:        
.\"
.\"     Man page for IS_BASE_DIGIT
.\"
.\" Author:      Paul A. Houghton - (paul.houghton@wcom.com)
.\" Created:     05/05/97 06:32
.\"
.\" Revision History: (See end of file for Revision Log)
.\"
.\"  Last Mod By:    $Author$
.\"  Last Mod:       $Date$
.\"  Version:        $Revision$
.\"
.\" $Id$
.\"
.TH IS_BASE_DIGIT 3  "05/05/97 06:32 (Common)"
.SH NAME
IS_BASE_DIGIT \- Test a character to see if it is a valid digit of the
specified base.
.SH SYNOPSIS
#include <Common.h>
.LP
BOOL IsBaseDigit(
.PD 0
.RS
.TP 10
char
digit,
.TP 10
int
base )
.SH ARGUMENTS
.TP
digit
the ASCII character value to test.
.TP
base
The base that the character should be a value of.
.SH DESCRIPTION
This function uses CharToInt(3) to verify a character is
a legal value for the base. 
.SH RETURNS
.TP
TRUE (1)
The character is a legal value of the base.
.TP
FALSE (0)
The character is out of range for the base.
.SH FILES
%INSTALL_INC_DIR%/Common.h
.SH "SEE ALSO"
Common(3), CHAR_TO_INT(3),
StringToInt(3), StringToUInt(3), StringToShort(3),
StringToUShort(3), StringToLong(3), StringToULong(3), StringToDouble(3)
.SH AUTHORS
Paul A. Houghton - (paul.houghton@wcom.com)

.\"
.\" Revision Log:
.\"
.\" $Log$
.\" Revision 2.1  1997/05/07 11:35:43  houghton
.\" Initial version.
.\"
.\"
