.\"
.\" Man page for IsBaseDigit
.\"
.\" $Id$
.\"
.\" $Log$
.\" Revision 1.1  1994/07/05  21:38:04  houghton
.\" Updated man pages for all libCommon functions.
.\"
.\"
.TH IsBaseDigit 3  "22 Jun 94 (Common)"
.SH NAME
IsBaseDigit \- Test a character to see if it is a valid digit of the
specified base.
.SH SYNOPSIS
#include <Common.h>
.LP
Bool IsBaseDigit(
.PD 0
.RS
.TP 10
char
digit,
.TP 10
int
base )
.SH ARGUMENTS
.TP
digit
the ASCII character value to test.
.TP
base
The base that the character should be a value of.
.SH DESCRIPTION
This function uses CharToInt(3) to verify a character is
a legal value for the base. 
.SH RETURNS
.TP
TRUE (1)
The character is a legal value of the base.
.TP
FALSE (0)
The character is out of range for the base.
.SH FILES
/usr/local/include/Common.h
.SH "SEE ALSO"
Common(3), CharToInt(3), StringToInt(3), StringToLong(3)
.SH AUTHORS
Paul Houghton - (houghton@cworld.wiltel.com) 

