.\"
.\" File:      LoggerTrim.3
.\" Project:   Common
.\" Desc:        
.\"
.\"     Man page for LoggerTrim
.\"
.\" Author:      Paul A. Houghton - (paul.houghton@wcom.com)
.\" Created:     6/21/94
.\"
.\" Revision History: (See end of file for Revision Log)
.\"
.\"  Last Mod By:    $Author$
.\"  Last Mod:       $Date$
.\"  Version:        $Revision$
.\"
.\" $Id$
.\"
.TH LoggerTrim 3  "05/05/97 04:47 (Common)"
.SH NAME
LoggerTrim \- Trim the log file
.SH SYNOPSIS
#include <Common.h>
.LP
void LoggerTrim( void )
.SH DESCRIPTION
Calling LoggerTrim cause the log file to be trimmed according to the
maxByteCount and timeIncrement parameters of LoggerInit(3).
.SH RETURNS
None
.SH FILES
.nf
%INSTALL_INC_DIR%/Common.h
%INSTALL_LIB_DIR%/libCommon.a
.SH "SEE ALSO"
.SH "SEE ALSO"
Common(3), LogLevelSetString(3), LogLevelFromString(3), LogLevelString(3),
LoggerInit(3), LoggerSetLogFile(3), LoggerSetOutputLevel(3),
LoggerSetDate(3), LoggerSetLoc(3), LoggerSetTee(3),
LoggerSetFunct(3), LoggerGetFunct(3), LoggerLevel(3), LoggerLoc(3),
Logger(3), LoggerArgs(3),
LOGITLOC(3), LOGIT(3), LOGFUNCT(3), LOGERROR(3) 
.SH AUTHORS
Paul A. Houghton - (paul.houghton@wcom.com)

.\"
.\" Revision Log:
.\"
.\" $Log$
.\" Revision 2.2  1998/09/24 14:30:05  houghton
.\" Reworked to replace directory names with Makefile variable value.
.\"
.\" Revision 2.1  1997/05/07 11:35:02  houghton
.\" Updated for release 2.01.02
.\"
.\" Revision 2.0  1995/10/28 17:34:50  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.1  1994/07/05  21:38:10  houghton
.\" Updated man pages for all libCommon functions.
.\"
.\"
