.\"
.\" Man page for MemberOfGroup
.\"
.\" $Id$
.\"
.\" $Log$
.\" Revision 2.1  1998/09/24 14:30:05  houghton
.\" Reworked to replace directory names with Makefile variable value.
.\"
.\" Revision 2.0  1995/10/28 17:34:50  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.1  1995/02/13  15:33:29  houghton
.\" New man pages for new functions.
.\"
.\"
.TH MemberOfGroup 3  "19 Aug 94"
.SH NAME
MemberOfGroup \- is the current user a member of a specific group.
.SH SYNOPSIS
#include <Common.h>
.LP
Bool MemberOfGroup(
.PD 0
.RS
.TP 15
gid_t
group )
.PD
.RE
.SH ARGUMENTS
.TP
group
the group id to check.
.SH DESCRIPTION
Returns TRUE if the current user id is a member of the group.
.SH RETURNS
.TP
TRUE
the use is a member of the group
.TP
FALSE
the use is not a member of the group.
.SH FILES
.nf
%INSTALL_INC_DIR%/Common.h
%INSTALL_LIB_DIR%/libCommon.a
.fn
.SH "SEE ALSO"
Common(3)
.SH AUTHORS
Paul Houghton x2309 - (houghton@shoe.wiltel.com) 

