.\"
.\" File:      SET_ERROR.3
.\" Project:   Common
.\" Desc:        
.\"
.\"     Man page for SET_ERROR() Ver: (Common.h 2.13)
.\"
.\" Author:      Paul A. Houghton - (paul.houghton@wcom.com)
.\" Created:     04/29/97 07:16
.\"
.\" Revision History: (See end of file for Revision Log)
.\"
.\"  Last Mod By:    $Author$
.\"  Last Mod:       $Date$
.\"  Version:        $Revision$
.\"
.\" $Id$
.\"
.TH SET_ERROR 3  "04/29/97 07:16 (Common)"
.SH NAME
SET_ERROR \- calls SetError(3) with default args.
#include <Common.h>
.LP
void SET_ERROR(
.PD 0
.RS
.TP 18
CommonErrorType
errorType,
.TP 18
int
errorValue )
.PD
.RE
.SH ARGUMENTS
.TP
errorType
the type of value in errorValue.
.TP
errorValue
error value representing the error.
.SH DESCRIPTION
This macro calls SetError(3) with __FILE__, __LINE__, closure = 0 and
errorDesc = 0.
.SH RETURNS
None.
.SH FILES
.PD 0
%INSTALL_INC_DIR%/Common.h
.PD
.SH "SEE ALSO"
Common(3), SetErrorHandler(3), GetErrorHandler(3),
Error(3), ErrorArgs(3), SetError(3), ErrorMesg(3), ErrorTypeString(3),
CommonErrorString(3),
SET_ERROR_CLOSURE(3), ERROR(3), ERROR_APP(3)
.SH AUTHORS
Paul A. Houghton - (paul.houghton@wcom.com)
.\"
.\" Revision Log:
.\"
.\" $Log$
.\" Revision 2.1  1997/05/07 11:35:02  houghton
.\" Updated for release 2.01.02
.\"
.\" Revision 2.0  1995/10/28 17:34:51  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.3  1994/07/05  21:50:35  houghton
.\" fixup man page comment header
.\"
.\" Revision 1.2  1994/07/05  21:38:11  houghton
.\" Updated man pages for all libCommon functions.
.\"
.\" Revision 1.1  1994/06/17  18:07:15  houghton
.\" New man pages ... what a concept!
.\"
.\"
