.\"
.\" Man page for StringToDouble
.\"
.\" $Id$
.\"
.\" $Log$
.\" Revision 2.0  1995/10/28 17:34:53  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.1  1995/02/13  15:33:30  houghton
.\" New man pages for new functions.
.\"
.\"
.TH StringToDouble 3  "19 Aug 94"
.SH NAME
StringToDouble \- Convert a string to an double
.SH SYNOPSIS
#include <Common.h>
.LP
double StringToDouble(
.PD 0
.RS
.TP 15
const char *
string,
.TP 15
int
base,
.TP 15
int
length )
.PD
.RE
.SH ARGUMENTS
.TP
string
the string to be converted.
.TP
base
the base of the string. A value of 0 cause the base to be determined
by the first two characters of the string. a leading '0' means octal
(base 8) and a leading '0x' or '0X' means hex (base 16).
.TP
length
the number of character to use for the conversion. A value of 0
means the string is NULL terminated.
.SH DESCRIPTION
Converts a character string to a double.
.SH RETURNS
the double value.
.SH FILES
.nf
/usr/local/include/Common.h
/usr/local/lib/libCommon.a
.fn
.SH "SEE ALSO"
Common(3), CHAR_TO_INT(3), StringToInt(3), StringToUInt(3),
StringToShort(3), StringToLong(3), StringToLong(3),
StringToULong(3), atoi(3)
.SH AUTHORS
Paul Houghton - (houghton@cworld.wiltel.com) 
