.\"
.\" Man page for strupr
.\"
.\" $Id$
.\"
.\" $Log$
.\" Revision 2.0  1995/10/28 17:34:58  houghton
.\" Move to Version 2.0
.\"
.\" Revision 1.1  1994/07/05  21:38:16  houghton
.\" Updated man pages for all libCommon functions.
.\"
.\"
.TH strupr 3  "22 Jun 94 (Common)"
.SH NAME
strupr \- convert a string to all upper case.
.SH SYNOPSIS
#include <Common.h>
.LP
char * strupr(
.PD 0
.RS
.TP 10
char *
text )
.PD
.RE
.SH ARGUMENTS
text
the string to be converted.
.SH DESCRIPTION
Converts the input string to all upper case.
.SH RETURNS
a pointer to the input string.
.SH FILES
.nf
%INSTALL_INC_DIR%/Common.h
%INSTALL_LIB_DIR%/libCommon.a
.fn
.SH "SEE ALSO"
Common(3), strlwr(3), toupper(3)
.SH AUTHORS
Paul Houghton - (houghton@cworld.wiltel.com) 

