.\"
.\" File:      template.3
.\" Project:   Common
.\" Desc:        
.\"
.\"     Man page for template
.\"
.\" Author:      Paul A. Houghton - (paul.houghton@wcom.com)
.\" Created:     05/07/97 06:21
.\"
.\" Revision History: (See end of file for Revision Log)
.\"
.\"  Last Mod By:    $Author$
.\"  Last Mod:       $Date$
.\"  Version:        $Revision$
.\"
.\" $Id$
.\"
.TH template 3  "05/07/97 06:21 (Common)"
.SH NAME
template \- 
.SH SYNOPSIS

.SH ARGUMENTS

.SH DESCRIPTION

.SH OPTIONS

.SH RETURNS

.SH ENVIRONMENT

.SH EXAMPLE

.SH FILES
.PD 0
.PD
.SH "SEE ALSO"

.SH AUTHORS
Paul A. Houghton - (paul.houghton@wcom.com)

.\"
.\" Revision Log:
.\"
.\" $Log$
.\"
