ARCH_C_SOURCES =			\
	../arch/src/strlwr.c		\
	../arch/src/strupr.c		\
	../arch/src/strdup.c		\
	../arch/src/CanExecute.c	\
	../arch/src/FileModeString.c	\
	../arch/src/ForeachFile.c	\
	../arch/src/MemberOfGroup.c	\


ARCH_DEFINES = 