# -*- Makefile -*-
#
# Makefile for libCommon src/arch/Sun5
#
# Created 07/17/97
#
# $Id$
#
#

ARCH_SRC_DIR	= ../arch/src
ARCH_DIR	= ../arch/$(arch)

ARCH_VPATH	= $(ARCH_DIR):$(ARCH_SRC_DIR)

ARCH_DEFINES	=
ARCH_INC	= -I$(ARCH_DIR)

ARCH_C_SOURCES	=		\
	strlwr.c		\
	strupr.c		\
	strdup.c		\
	CanExecute.c		\
	FileModeString.c	\
	ForeachFile.c		\
	MemberOfGroup.c		\


ARCH_USER_H_INCS	= 		\
	$(ARCH_DIR)/CommonConfig.h	\

ARCH_C_HEADERS		= 		\
	$(ARCH_DIR)/CommonConfig.h	\

#
# $Log$
#
