#
# -*- Makefile -*-
#
# Makefile for libCommon src/arch/Linux
#
# Created 11/20/95
#
# $Id$
#
#

ARCH_DEFINES	=
ARCH_INCDIR	= -I../arch/$(arch)

ARCH_C_SOURCES		=

ARCH_USER_H_INCS	= ../arch/$(arch)/CommonConfig.h

ARCH_C_HEADERS		= ../arch/$(arch)/CommonConfig.h

#
# $Log$
# Revision 2.1  1995/12/02 02:12:31  houghton
# Initial Version.
#
#
